name: e_commerce_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.5.0
  cupertino_icons: ^1.0.9
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_carousel_widget: ^3.1.0
  flutter_dash: ^1.0.0
  flutter_native_splash: ^2.4.8
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/571467967_2221330675054332_5857262115784261188_n.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
flutter_native_splash:
  color: "#6E6190"
  #color_dark: "#042a49"
  #background_image:      "assets/background.png"
  #background_image_dark: "assets/dark-background.png"
  image: assets/images/E-Commerce-PNG-Transparent.png
  #image_dark:          assets/splash-invert.png
  #branding:      assets/dart.png
  #branding_dark: assets/dart_dark.png
  fullscreen: true
  android_12:
    # background color
    color: "#6E6190"
    # color_dark: "#042a49"
    image: assets/images/E-Commerce-PNG-Transparent.png
    # image_dark: assets/images/logo/logo-splash2.png
    # center-logo background color
    # icon_background_color: "#111111"
    # icon_background_color_dark: "#eeeeee"
    #branding:      assets/dart.png
    #branding_dark: assets/dart_dark.png
